# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/redditdumps',
                'doc_host': 'https://wuqui.github.io',
                'git_url': 'https://github.com/wuqui/redditdumps',
                'lib_path': 'redditdumps'},
  'syms': {'redditdumps.core': {'redditdumps.core.foo': ('core.html#foo', 'redditdumps/core.py')}}}
