# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/redditdumps',
                'doc_host': 'https://wuqui.github.io',
                'git_url': 'https://github.com/wuqui/redditdumps',
                'lib_path': 'redditdumps'},
  'syms': { 'redditdumps.core': { 'redditdumps.core.add_one': ('core.html#add_one', 'redditdumps/core.py'),
                                  'redditdumps.core.get_docs': ('core.html#get_docs', 'redditdumps/core.py'),
                                  'redditdumps.core.train_model': ('core.html#train_model', 'redditdumps/core.py')}}}
